### ISSUE TITLE
Clarify the use of "refs" over "url"

### ISSUE THREAD

**Issue by lamby** [bdrung/image-release-spec#3]
Hi, please clarify the use of "refs" over "url" in the spec (or change it) — the latter is surely self-documenting…?

**Comment by bdrung** [comment]
Oh. "refs" was a mistake on my side. I wanted to use "href" from the JSON API specification. Should we follow the JSON API and the HTML name or better use the self-documenting "url"?

**Comment by lamby** [comment]
I'm easy re. url vs href. They are both equally self-documenting for anyone who has, like, used the web :)

**Comment by lamby** [comment]
\o/
