### ISSUE TITLE
Please clarify GPG signature scheme

### ISSUE THREAD

**Issue by lamby** [bdrung/image-release-spec#7]
Re. the signatures, unless I'm missing something if I compromise this JSON file I can point ``meta['signature']`` to ``http://my-own-server.com/signature.gpg``. Or I just replace the signature file if its on the same server. Unless there is some idea of "this can only be signed by X", I'm not sure what the signature scheme adds?

**Comment by bdrung** [comment]
The signature could be compromised that way, but the attacker needs to sign the file with the same GPG key or otherwise the user could detect the attack.

**Comment by lamby** [comment]
(Again, please clarify on the spec itself, surely?)
